language: node_js
node_js:
  - "12"

services:
  - docker

before_script:
  - npm install

script:
  - npm test
  - docker build -f Docker/Dockerfile -t property-locator:dev .

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  - docker tag property-locator $DOCKER_USER/property-locator:dev
  - docker push $DOCKER_USER/property-locator:dev
