sudo: required

services:
  - docker

script:
  - docker-compose up --build -d

after_success:
  - docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
  - docker tag property-locator $DOCKER_USER/property-locator:dev
  - docker push $DOCKER_USER/property-locator:dev
